### ISSUE TITLE
Misleading bandwidth recommendation

### ISSUE THREAD

**Issue by LXHeinze** [MicrosoftDocs/dynamics-365-mixed-reality#16]
The document states "The recommended bandwidth for optimal performance of Remote Assist is 1.5 MB/s", however looking at the same requirements in the Teams documentation it should be referred to as "1.5 Mbps", otherwise someone could read "MB" and megabytes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d114e81-25d6-54b1-47f3-68305840b8f8
* Version Independent ID: 585f1e1a-4d76-27e4-a1b9-4976f413cc9b
* Content: [Requirements for Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/requirements#feedback)
* Content Source: [mr-docs/remote-assist/requirements.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/requirements.md)
* Service: **crm-online**
* GitHub Login: @jevertt
* Microsoft Alias: **jevertt**

**Comment by BryceHolmes** [comment]
Fixed
