### ISSUE TITLE
Solution Download Link

### ISSUE THREAD

**Issue by bartsneary** [MicrosoftDocs/dynamics-365-mixed-reality#2]
Above, under "Import the Product Visualize solution", there's a bullet instructing us to "Download the Product Visualize solution to your PC".  There's no link to that solution and I can't find one when searching for it using Bing or Google or looking on AppSource.  Can you put a link to it in this doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bd6c2b-4df5-8dc3-6be5-cdc8415e9629
* Version Independent ID: 34ee7a63-3cdd-63f6-3b1d-d85a3d0287ab
* Content: [Administrator Guide for Dynamics 365 Product Visualize - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/product-visualize/admin-guide)
* Content Source: [mr-docs/product-visualize/admin-guide.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/product-visualize/admin-guide.md)
* Service: **crm-online**
* GitHub Login: @mamithan
* Microsoft Alias: **mamithan**

**Comment by cwalvander** [comment]
I have the same problem, reset my sandbox (twice) and still no product visualize solution available.

**Comment by mamithan** [comment]
Should be corrected now!
https://docs.microsoft.com/en-us/dynamics365/mixed-reality/product-visualize/admin-guide#install-the-product-visualize-control

**Comment by sbmjais** [comment]
The document is updated as per the new setup steps: [https://docs.microsoft.com/en-us/dynamics365/mixed-reality/product-visualize/setup](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/product-visualize/setup).
Closing this issue.
