### ISSUE TITLE
Voice Command Instructions Appear to be Incorrect

### ISSUE THREAD

**Issue by ARGs-code** [MicrosoftDocs/dynamics-365-mixed-reality#27]
Current page reads- To use a voice command, say “Dynamics 365 Remote Assist,” and then say one of the voice commands in the following table. For example, say "Dynamics 365 Remote Assist, Move"

However when testing this seems to fail to trigger the voice command 80-90% of the time. However, saying "Remote Assist, x" where x is your voice command seems to be the actual trigger for all voice commands listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa7e6ec-0bda-b259-7bd7-0279fd7f8750
* Version Independent ID: cfecc5d2-ab49-2eeb-1012-0b225844466b
* Content: [Dynamics 365 Remote Assist user guide (for HoloLens) - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/user-guide#feedback)
* Content Source: [mr-docs/remote-assist/user-guide.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/user-guide.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by m-hartmann** [comment]
Hello Andrew, 
Thanks for sharing this valuable feedback and apologies for the delay to get back to you on this issue. I recently took over Remote Assist docs and finally go to work through the open issues. 
Your point is absolutely valid and you are right about the trigger word. The docs were already updated with that a while ago so I'm closing this issue. Please keep your feedback coming!

Thanks, 
Michael
