### ISSUE TITLE
Subscription link missing

### ISSUE THREAD

**Issue by SamiraAtMicrosoft** [MicrosoftDocs/dynamics-365-mixed-reality#29]
Under the "What you'll need" section, the link to "A subscription to Dynamics 365 Remote Assist" does not point to anywhere that a user can create a subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854631f6-64bb-eb1a-78c1-bbf1e0d87ad9
* Version Independent ID: 39a4c324-d119-9de6-04b2-4547833b96ce
* Content: [Set up and use Microsoft Teams with Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/use-microsoft-teams-with-remote-assist#feedback)
* Content Source: [mr-docs/remote-assist/use-microsoft-teams-with-remote-assist.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/use-microsoft-teams-with-remote-assist.md)
* Service: **crm-online**
* GitHub Login: @bencorn
* Microsoft Alias: **bencorn**

**Comment by BryceHolmes** [comment]
Old topic. No longer relevant.
