### ISSUE TITLE
 Return to Remote Assist 

### ISSUE THREAD

**Issue by MRW-Eric** [MicrosoftDocs/dynamics-365-mixed-reality#35]
Once I have left RA to view another app, how can I get back to RA?
On HL2 I have to spawn a new instance of RA which seems odd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0a478c8-527f-59a5-4bc8-3ed650f5e78a
* Version Independent ID: b92db213-9c9b-94ce-e7bb-2c3b528346a5
* Content: [Use Dynamics 365 Remote Assist to get help in a different HoloLens app - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/get-help-hololens-app-hololens#feedback)
* Content Source: [mr-docs/remote-assist/get-help-holoLens-app-hololens.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/get-help-holoLens-app-hololens.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by v-wendysmith** [comment]
@MRW-Eric I hope this issues has been resolved by now! Apologies for such a delayed response. I'm a new writer to the team and will be more responsive in handling these issues. If you are still experiencing trouble, you can return to Remote Assist by going back to the Shell, and then clicking on the Live Cube that was placed in your space when you launched Remote Assist previously. Re-launching an app directly from OS menu will result in a new Live Cube placed in your space each time.
Related documentation:
https://learn.microsoft.com/en-us/windows/mixed-reality/design/system-gesture
https://learn.microsoft.com/en-us/windows/mixed-reality/design/app-model#placement-and-launch
Thank you.
