### ISSUE TITLE
Delpoying Microsoft Teams licenses link points to a 404 page

### ISSUE THREAD

**Issue by matthew0102** [MicrosoftDocs/dynamics-365-mixed-reality#38]
Upon clicking the link for Deploying Microsoft Teams licenses, I was redirected to a 404 page. Below is the screenshot of the link.
![image](https://user-images.githubusercontent.com/50011220/84368656-6e643c00-ac08-11ea-9a81-b0d7daa47a57.png)

The page it links to looks like this
![image](https://user-images.githubusercontent.com/50011220/84369190-0feb8d80-ac09-11ea-8342-826ddbf6b361.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a264db71-4fa7-3382-5d12-ec9bf35247fe
* Version Independent ID: 9e968d81-a530-009c-3245-4047a7c3659c
* Content: [Deploy Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/deploy-remote-assist)
* Content Source: [mr-docs/remote-assist/deploy-remote-assist.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/deploy-remote-assist.md)
* Service: **crm-online**
* GitHub Login: @xonatia
* Microsoft Alias: **xolee**

**Comment by BryceHolmes** [comment]
Removed bad link.
