### ISSUE TITLE
Need to update Note to reflect Deeplink is available on iOS too, and not only Android

### ISSUE THREAD

**Issue by hegate** [MicrosoftDocs/dynamics-365-mixed-reality#39]
FSM now integrates with RA in iOS as well per this https://docs.microsoft.com/en-us/dynamics365/field-service/field-service-version-history-mobile#104847, doc must be updated.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 694deac7-a24f-ed7d-2175-3274f4aa1873
* Version Independent ID: d53ae218-87cb-6e46-8dc9-11821b79d1dd
* Content: [Integrate Dynamics 365 Remote Assist with Dynamics 365 Field Service - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/troubleshoot-field-service?source=docs)
* Content Source: [mr-docs/remote-assist/troubleshoot-field-service.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/troubleshoot-field-service.md)
* Service: **dynamics-365-mixed-reality-remote-assist**
* Technology: **remote-assist**
* GitHub Login: @bencorn
* Microsoft Alias: **daclar**

**Comment by BryceHolmes** [comment]
Fixed
