### ISSUE TITLE
PCF Control: 'Description' Should be 'Topic'

### ISSUE THREAD

**Issue by RickyRoeslerMS** [MicrosoftDocs/dynamics-365-mixed-reality#4]
Step 6 of 'Customize the Opportunity page' says to add a "Description" field but should say "Topic" field

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bd6c2b-4df5-8dc3-6be5-cdc8415e9629
* Version Independent ID: 34ee7a63-3cdd-63f6-3b1d-d85a3d0287ab
* Content: [Administrator guide for Dynamics 365 Product Visualize - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/product-visualize/admin-guide)
* Content Source: [mr-docs/product-visualize/admin-guide.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/product-visualize/admin-guide.md)
* Service: **crm-online**
* GitHub Login: @rroesler
* Microsoft Alias: **rroesler**

**Comment by sbmjais** [comment]
Hi @RickyRoeslerMS - The document is updated as per the new setup steps: [https://docs.microsoft.com/en-us/dynamics365/mixed-reality/product-visualize/setup](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/product-visualize/setup).
Closing this issue.
