### ISSUE TITLE
Return to calling app after call does not work in Kiosk Mode.

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [MicrosoftDocs/dynamics-365-mixed-reality#40]
I trigger Remote Assist from a custom app as described on 
https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/protocol-activation.md#example-of-launching-dynamics-365-remote-assist-from-your-app-with-optional-returnto-field

In "Normal" Mode Remote Assist is started and after the Call the user is redirected to my custom App as expected.
In "Kiosk" Mode (with my custom App being started), starting Remote Assist works fine but after finishing the call, Remote Assist remains open and the user cannot get back to my custom App.

**Comment by v-wendysmith** [comment]
@BewaControl-ReneDivossen hopefully the issue has been resolved by now. Apologies for such a delay. I'm a new writer to the team and working on issues. If you still have an issue, please open a support ticket. Thank you.
