### ISSUE TITLE
Launch Dynamics 365 Remote Assist from another app (protocol activation) doesn't work

### ISSUE THREAD

**Issue by tienloctran** [MicrosoftDocs/dynamics-365-mixed-reality#41]
The URI would look something like this: ms-voip-video:?contactids=\<contactID\>. (contactID = Azure Object ID). The URI has 2 parts: “ms-voip-video” to launch the remote assist and “contactID”  identifies who we want to call. 

My issue: This URI worked well before but from last 2 weeks it suddenly stops working .  
-	“ms voip video”: still working -> Remote assist is launched from my app
-	ID part is not working. I cannot reach to designated person.
Honestly I don’t really understand why it happens, I am creating this topic in hope of hearing your opinions and experience about this problem. I am thinking about the Security issue, the security doesn’t let me get the Object ID from Azure database.

**Comment by v-wendysmith** [comment]
@tienloctran My apologies that you are just now receiving a response to your question. I'm a new writer to the team and will be more responsive. Are you still having an issue?
