### ISSUE TITLE
Record a Call Using the Windows Game Bar Link is Dead

### ISSUE THREAD

**Issue by ARGs-code** [MicrosoftDocs/dynamics-365-mixed-reality#43]
The link on this line "Learn more about how a Teams desktop user can record a call using Windows Game Bar." returns 404

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcab2a88-4a33-33f7-d4b2-85b1abad8c8e
* Version Independent ID: e5629e17-b6ba-52f1-1d9a-ffd9b5bce2e9
* Content: [Record calls in Dynamics 365 Remote Assist on HoloLens - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/record-calls-hololens)
* Content Source: [mr-docs/remote-assist/record-calls-hololens.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/record-calls-hololens.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by sophiasysun** [comment]
Thanks for letting me know - I've updated it in our docs and the change should go out around 9/1.

**Comment by BryceHolmes** [comment]
Fixed.
