### ISSUE TITLE
Restart hololens links need a new link.

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/dynamics-365-mixed-reality#44]
Hello RA team,

I was browsing your Doc set and found an two older links that directed to support which now re-directs to the wrong page (not sure why it goes to HL1 hardware of all things). Would you please update the "restart your HoloLens." links to https://docs.microsoft.com/en-us/hololens/hololens-recovery ?
Thanks!
-Evan

P.S. I tried to submit a PR for your approval, but the edit button on your public repo takes me to a 404. Couldn't find this file to make a PR myself when I went poking around your repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fee1a575-32b4-17a1-ced3-ba8276e9b6fa
* Version Independent ID: 70ffb541-c28d-2ea9-c23a-899f3f0d408d
* Content: [Dynamics 365 Remote Assist frequently asked questions - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/faq-hololens)
* Content Source: [mr-docs/remote-assist/faq-hololens.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/faq-hololens.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by BryceHolmes** [comment]
Fixed.
