### ISSUE TITLE
HoloLens 2 has RA preinstalled

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/dynamics-365-mixed-reality#47]
Hello,

In this section: https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/deploy-remote-assist#steps-for-hololens-and-hololens-2

HoloLens users are prompted to download the app from the store. HoloLens (1st gen) users will need to go through this flow. However on HoloLens 2 all devices come with Remote Assist preinstalled, although HoloLens 2 devices initialized before the Windows Holographic, version 2004 update will need to update the app before it can be fully used, but can be done by selecting it from the Start menu.

May I suggest changing...

1. Go to the Start menu and then select Microsoft Store.
1. Search for and download Dynamics 365 Remote Assist and launch the app.

TO

1. Go to the Start menu and then if Remote Assist is present launch it to update or start the app.
    1. If it is not present on the device select Microsoft Store.
    1. Search for and download Dynamics 365 Remote Assist and launch the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a264db71-4fa7-3382-5d12-ec9bf35247fe
* Version Independent ID: 9e968d81-a530-009c-3245-4047a7c3659c
* Content: [Deploy Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/deploy-remote-assist)
* Content Source: [mr-docs/remote-assist/deploy-remote-assist.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/deploy-remote-assist.md)
* Service: **crm-online**
* GitHub Login: @xonatia
* Microsoft Alias: **xolee**

**Comment by m-hartmann** [comment]
Hello Evan,
Thanks for sharing this valuable feedback and apologies for the delay to get back to you on this issue. I recently took over Remote Assist docs and finally got around to work through the open issues.
You're absolutely right about the preinstalled RA app. I'll update the docs accordingly. When I merge the update, it'll automatically close this issue. Please keep your feedback coming!

Thanks,
Michael
