### ISSUE TITLE
Can the "returnto" field be used on mobile devices?

### ISSUE THREAD

**Issue by Corona21** [MicrosoftDocs/dynamics-365-mixed-reality#48]
Could you please specify if the returnto field can also be used on mobile devices (ramobile://)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c4faad9-003f-eed0-c611-2fb826b5deca
* Version Independent ID: 05e43b7d-583d-b658-609c-f35512f578ca
* Content: [Launch Dynamics 365 Remote Assist from another app - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/protocol-activation#feedback)
* Content Source: [mr-docs/remote-assist/protocol-activation.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/protocol-activation.md)
* Service: **crm-online**
* GitHub Login: @bencorn
* Microsoft Alias: **bencorn**

**Comment by v-wendysmith** [comment]
@Corona21 I apologize you are not getting a response to your question until now! I'm a new writer to the team so I'll be responding to these questions much more quickly. To answer your question, no, the returnTo parameter is only supported for RA HoloLens and not on mobile.
