### ISSUE TITLE
Note formatting needs a fix

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/dynamics-365-mixed-reality#49]
Hello,

The NOTE formatting in this section https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/requirements#dynamics-365-remote-assist-app-user Is broken. 

The ! is outside the box.

Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d114e81-25d6-54b1-47f3-68305840b8f8
* Version Independent ID: 585f1e1a-4d76-27e4-a1b9-4976f413cc9b
* Content: [Requirements for Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/requirements#licensing-and-product-requirements-per-role)
* Content Source: [mr-docs/remote-assist/requirements.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/requirements.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by BryceHolmes** [comment]
Fixed
