### ISSUE TITLE
Visio Add-in for Microsoft Dynamics 365 Layout Setup

### ISSUE THREAD

**Issue by rainbowLCH000** [MicrosoftDocs/dynamics-365-mixed-reality#5]
error：This Add-In is only avaliable in English

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e10fe3d-8467-8be1-4632-3fca2bc4d331
* Version Independent ID: 0008c819-7b7c-5c0e-2577-4124ebe1b78b
* Content: [Use Dynamics 365 Import Tool (Preview) to prepare 3D models to work with Dynamics 365 Layout - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/import-tool/layout#feedback)
* Content Source: [mr-docs/import-tool/layout.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/import-tool/layout.md)
* Service: **crm-online**
* GitHub Login: @BryceHo
* Microsoft Alias: **BryceHo**

**Comment by BryceHo** [comment]
Yes, the whole Layout app is only available in English at this time. English-only availability is noted in the FAQ.

**Comment by jmlg10** [comment]
So does it mean that the Windows needs to run in English too or just Visio

**Comment by jmlg10** [comment]
Is it a way to place teh 3D components in 2D in Visio and get them automatically in Layout?
and in the other way, when a Layoiut is done with 3D objects placed in 3D, is it possible to update the Visio drawing?
