### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by imtemi** [MicrosoftDocs/dynamics-365-mixed-reality#50]
[There is a spelling mistake on point 4 of the section with title: What Remote Assist features are not available for your customer, if they join the call as an unauthenticated call [participant?]]([https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/one-time-call#what-remote-assist-features-are-not-available-for-your-customer-if-they-join-the-call-as-an-unauthenticated-call-participant])

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e312080c-4d3c-d30c-91cb-2b3906d50e01
* Version Independent ID: 44fb8bd5-fe16-b37a-6329-522cec1200c8
* Content: [Invite user to join one-time call - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/one-time-call)
* Content Source: [mr-docs/remote-assist/one-time-call.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/one-time-call.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by BryceHolmes** [comment]
Fixed
