### ISSUE TITLE
Update Install the Apps for HoloLens 2 devices

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/dynamics-365-mixed-reality#51]
Hello, 

In this section much of the information is targeted towards HoloLens (1st gen). https://docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/setup-step-three#install-the-hololens-app  I'd appreciate it if we could update this section that that users with HoloLens 2 could use the simplified instructions. 
(note I didn't re-add links from copied text.)

We recommend that you update HoloLens to newer versions when they become available. For information about how to use Windows Update for Business, see Manage updates to HoloLens. You may also [manually update your HoloLens](https://docs.microsoft.com/hololens/hololens-update-hololens). We also suggest keeping your HoloLens app up-to-date.

### For HoloLens 2 devices:
All HoloLens 2 devices meet the OS requirements as well as have Dynamics 365 Guides pre-installed as an In-box app. You may choose to [update your Guides app from the Microsoft Store](https://docs.microsoft.com/en-us/hololens/holographic-store-apps#update-apps) as needed. 

On your HoloLens 2 device, use the [Start gesture](https://docs.microsoft.com/en-us/hololens/hololens2-basic-usage#start-gesture) to open the start menu. You should find Guides pinned to the start menu. If it's been unpinned, select the **All apps** button to find it. Select **Guides** to launch the app. 

### For HoloLens (1st gen) devces:
Make sure that HoloLens is running build 10.0.17134 or later. 

On your HoloLens, use the bloom gesture to open the start menu. Then open the Microsoft Store app, and search for "Dynamics 365 Guides."

To download and install the Dynamics 365 Guides app, select Install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55f5d2d6-2f63-00e0-ce6d-d0682f6f5a22
* Version Independent ID: ec6a2c84-1595-4144-f3d7-346e7fb198f0
* Content: [Download and install the Dynamics 365 Guides apps (PC and HoloLens) - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/setup-step-three#install-the-hololens-app)
* Content Source: [mr-docs/guides/setup-step-three.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/guides/setup-step-three.md)
* Service: **crm-online**
* GitHub Login: @Mamaylya
* Microsoft Alias: **mamaylya**

**Comment by BryceHolmes** [comment]
@evmill, thank you for your detailed feedback. We'll working on adding more updates for HoloLens 2.
