### ISSUE TITLE
Guidance on customizing the Bookings Pane is lacking.

### ISSUE THREAD

**Issue by jwittner** [MicrosoftDocs/dynamics-365-mixed-reality#52]
Information that would be useful:

* How to find the right view to modify?
  * [Other docs](https://docs.microsoft.com/en-us/dynamics365/field-service/remote-assist-hololens#set-up-field-service-for-the-hololens) suggest it may be "My Bookings for Today" or "My In Progress Bookings". 
    * Is that the right view for the HoloLens? 
    * Is it used by other applications?
      * Can I select what view is used by the HoloLens App?
    * These docs also don't provide the right or clear guidance to get to the Customization area of D365.
* Do I need a column to see the PowerBI links as shown in the example?
  * It's unclear what column would drive this link currently.

Our use case - we want to add a link to this Booking pane that can launch our own custom application directly from the work order pane. Is this possible? How would I go about setting this up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89d1dae4-a0cc-757b-9156-2dcf8915752f
* Version Independent ID: d43356b6-97ea-0f27-cf12-ac431dc501ff
* Content: [Update a Dynamics 365 Field Service booking in Dynamics 365 Remote Assist on HoloLens - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/update-field-service-booking-hololens#open-a-power-bi-dashboard-from-a-dynamics-365-field-service-booking)
* Content Source: [mr-docs/remote-assist/update-field-service-booking-hololens.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/remote-assist/update-field-service-booking-hololens.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun

**Comment by m-hartmann** [comment]
Hello Josh @jwittner - thanks for your feedback and apologies for getting back with such a long delay. We recently took over the doc work for Dynamics 365 MR apps and Field Service. We have a backlog item created to revise the customization section all-up and I will take your feedback into consideration when we work on it. If you were able to find out on your end what to customize to meet your needs, please let me know. I'm closing the issue and will link it to my backlog work item. Feel free to re-open it or create a new one if you find more issues.  

Many thanks, 
Michael

**Comment by jwittner** [comment]
I've since moved on from this work, but never did get it sorted out.
