### ISSUE TITLE
View same hologram on Hololens and Teams call

### ISSUE THREAD

**Issue by aarushi-mittal** [MicrosoftDocs/dynamics-365-mixed-reality#55]
Hello Team,

 I came across this passage from the official documentation.
_Field of view (FOV): The greater the device's field of view, the more holograms you can see at once. During a Dynamics 365 Remote Assist call, the Teams user can see all the holograms in the Dynamics 365 Remote Assist HoloLens user's space, but the Dynamics 365 Remote Assist HoloLens user can only see the holograms that are within their field of view._
[https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/ra-overview#learn-more-about-mixed-reality](url)

Kindly suggest if the hologram that the hololens user will be able to see will also be available to the Ms Teams call user.

Regards,
Aarushi

**Comment by v-wendysmith** [comment]
@aarushi-mittal, I'm a technical writer new to the Remote Assist team. Both users see the same thing, so I'm changing the documentation to say: "During a Dynamics 365 Remote Assist call, both the Dynamics 365 Remote Assist HoloLens user and the Teams user see the holograms that are within the HoloLens user's field of view." Thank you
