### ISSUE TITLE
How to share .glb files

### ISSUE THREAD

**Issue by aarushi-mittal** [MicrosoftDocs/dynamics-365-mixed-reality#56]
Hello Team,

How can we share holograms (.glb) files with other team members while on a teams call with a Hololens (both connecting using Dnamics 365)

Regards,
Aarushi

**Comment by v-wendysmith** [comment]
Hello @aarushi-mittal. I'm new to the Remote Assist team as a technical writer. Currently .glb files cannot be shared through file sharing using OneDrive. This idea is not currently on the product team's roadmap. However, if you are interested in having the product team look into this idea, please provide your use case and the file formats you're interested in sharing on the Guides User's Forum https://community.dynamics.com/365/guides/f/dynamics-365-guides-forum. Thank you.
