### ISSUE TITLE
Image for Remote Assist "take a picture"  may not be correct.  Looks like image for "type a message"

### ISSUE THREAD

**Issue by MattHoag-MS** [MicrosoftDocs/dynamics-365-mixed-reality#59]
Image for Remote Assist "take a picture"  may not be correct.  Looks like image for "type a message" 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dbc679-c946-b3ea-b491-a8cf57bddcf1
* Version Independent ID: aff224f3-bccd-130e-7934-65bc2c4df19c
* Content: [Take a photo and save it to a Dynamics 365 Field Service booking in Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/take-snapshot-save-booking-hololens)
* Content Source: [mr-docs/remote-assist/take-snapshot-save-booking-hololens.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/remote-assist/take-snapshot-save-booking-hololens.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by sophiasysun** [comment]
Hi all, I left this team in October. @Amara ***@***.***>, a PM on Remote Assist, can point you to someone on the team who can update this documentation.
