### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joyjaz** [MicrosoftDocs/dynamics-365-mixed-reality#61]
[Enter feedback here]
The link for learning more about deploying Remote Assist is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d114e81-25d6-54b1-47f3-68305840b8f8
* Version Independent ID: 585f1e1a-4d76-27e4-a1b9-4976f413cc9b
* Content: [Requirements for Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/requirements)
* Content Source: [mr-docs/remote-assist/requirements.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/remote-assist/requirements.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by sophiasysun** [comment]
Hi all, I no longer work on this team - please follow up with @Amara ***@***.***> instead.

**Comment by BryceHolmes** [comment]
Fixed
