### ISSUE TITLE
Remote AssistのためのURLとポート要件の表記について

### ISSUE THREAD

**Issue by kaztoyota** [MicrosoftDocs/dynamics-365-mixed-reality#62]
[フィードバックをこちらに入力してください]
URLとポート情報の中の *.teams.microsoft.com 部分について、O365用のページと表現方法が異なっておりますので、統一していただけないでしょうか？
Firewallへ設定を入れる際に、異なる表現方法だと二重に登録が必要なためです。
O365用のページは下記URLのものを参照しました。
https://docs.microsoft.com/ja-jp/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
お手数をおかけしますが、どうぞよろしくお願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5d114e81-25d6-54b1-47f3-68305840b8f8
* Version Independent ID: 585f1e1a-4d76-27e4-a1b9-4976f413cc9b
* Content: [Dynamics 365 Remote Assist の要件 - Dynamics 365 Mixed Reality](https://docs.microsoft.com/ja-jp/dynamics365/mixed-reality/remote-assist/requirements#network-requirements)
* Content Source: [mr-docs/remote-assist/requirements.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/remote-assist/requirements.md)
* Service: **crm-online**
* GitHub Login: @sophiasysun
* Microsoft Alias: **sopsun**

**Comment by v-wendysmith** [comment]
Hello @kaztoyota. I'm a new writer to the Mixed Reality team so I apologize for the delay in a response. I spoke with engineering. The reason for the differences is that Remote Assist lists the minimum requirements for that application. Office 365 covers requirements for Office 365 in general. Sorry that we cannot unify the requirements.

**Comment by kaztoyota** [comment]
Thank you for the update. So these requirements are technically different, correct? Hope dev team will match the network requirements in the future version as Teams and Remote Assists are both used in the same network.

Kaz
