### ISSUE TITLE
Possible conflicting information 

### ISSUE THREAD

**Issue by cakriwut** [MicrosoftDocs/dynamics-365-mixed-reality#68]
[Enter feedback here]
I am referring to contradicting information between - https://docs.microsoft.com/en-us/power-platform/admin/control-user-access (Article A), and this page (Article B) on the **nested security group**.

The Article A , mentioned that nested security group is supported. However the admin must add nested security group users manually to Dataverse Environment in home.dynamics.com.

The Article B, mentioned that nested security group arent supported.

My own testing, statement in Article A is correct. I have to add the nested security group users manually to Dataverse Environment and then assign security roles.

Question to product team:
1. Is nested security group supported? 
2. Which Article A or Article B contains correct information regarding to nested security group for D365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257df970-b2d9-b287-f553-59d0d783129b
* Version Independent ID: bc8b3d7b-d0c0-b3ab-beb7-98fe4381132f
* Content: [Restrict access to an environment in Dynamics 365 Guides by using security groups - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/admin-security#feedback)
* Content Source: [mr-docs/guides/admin-security.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/guides/admin-security.md)
* Service: **dynamics-365-guides**
* GitHub Login: @Mamaylya
* Microsoft Alias: **mamaylya**

**Comment by BryceHolmes** [comment]
Thank you for reporting this discrepancy. We're checking on this now.

**Comment by cakriwut** [comment]
Hi @BryceHolmes , thanks for looking into the matter. 
May I know if you have any timeline in mind for the update?

**Comment by BryceHolmes** [comment]
Hi Riwut. Thank you for following up. I don't have an exact timeline for the update, but I'm checking again with the folks that can answer this question.

**Comment by BryceHolmes** [comment]
Hi. I just wanted to follow up and let you know that no one knows of any reason why Guides has a different implementation of nested security groups than the Power Platform, so we're going to update the topic that you referred to. Thanks again for drawing our attention to this!

**Comment by BryceHolmes** [comment]
Fixed
