### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/dynamics-365-mixed-reality#69]
The link in the opening paragraph is broken:
https://github.com/MicrosoftDocs/dynamics-365-mixed-reality-pr/blob/ra-10-1-working/mr-docs/remote-assist/common-deployment-scenarios.md#scenario-3-vendors-and-customers-join-one-time-call

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 444a8040-b454-3dff-ae68-f0eaba088c58
* Version Independent ID: b7441f45-359b-a43f-f1cd-d517c38896ee
* Content: [Set up Microsoft Teams for Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/set-up-teams)
* Content Source: [mr-docs/remote-assist/set-up-teams.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/remote-assist/set-up-teams.md)
* Service: **crm-online**
* GitHub Login: @amaraanigbo
* Microsoft Alias: **soanigbo**

**Comment by BryceHolmes** [comment]
Fixed
