### ISSUE TITLE
Users Added to AAD Security Groups are not Added to Associated Dynamics 365 Team

### ISSUE THREAD

**Issue by ARGs-code** [MicrosoftDocs/dynamics-365-mixed-reality#70]
We have been following the documentation on the linked page in order to attempt to streamline assignment of Dynamics 365 Guides licenses and Security Roles. But it is not functioning as expected. I am trying to see if we are fundamentally misunderstanding something in the documentation.

It seems that we should be able to  

- Create an AAD Security Group

- Create a Team in our Dynamics Environment Associated with the Security Group

- Assign Security Roles to the Team

- The result should be that by assigning users to the AAD Group, they should inherit the security roles for the Dynamics Environment from the Team.

But we do not see any users being added to the Team when added to the AAD Group. Manually trying to add them via the Team Form Business view in the Guides Power App results in an error.

We have setup an AAD Security group and connected Dynamics 365 Licenses to it.

We have setup a Team on our Guides Environment, following the steps outlined here
https://docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/admin-assign-role-groups#option-2-assign-a-dynamics-365-guides-role-to-a-group-team

Any suggestions or guidance would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9f6e98a-f056-a6ae-d6a7-3d49e379071d
* Version Independent ID: 8646766f-be12-f63c-16e3-0a953bc8331f
* Content: [Assign Dynamics 365 Guides Author and Operator roles to an Azure Active Directory group - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/admin-assign-role-groups)
* Content Source: [mr-docs/guides/admin-assign-role-groups.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/guides/admin-assign-role-groups.md)
* Service: **dynamics-365-guides**
* GitHub Login: @MattHoag-MS
* Microsoft Alias: **v-mhoag**

**Comment by ARGs-code** [comment]
Trying to manually add members to the Team by opening it in the Guides Power App results in an error message
![dca62a1cd7a59dd995de6460fa528f5e](https://user-images.githubusercontent.com/15038504/148418601-74fb3634-0561-439c-b014-3720fd0765bd.png)

**Comment by BryceHolmes** [comment]
Hi. When a user is added to the AAD group, it doesn’t show up in the team until the user logs in. That might be the issue you're experiencing. If not, please file a support ticket so an engineer can investigate. Here's info on filing a support ticket:

1.	Go to https://dynamics.microsoft.com/support/.
2.	Under **Customer Engagement help + support**, select **GET SUPPORT**.
3.	Find a phone number or submit a support request through the admin center.

**Comment by ARGs-code** [comment]
That was it. Thank you very much BryceHolmes for the information.

Adding this as a note in the documentation would be very helpful as we were trying to test the flow of permissions before having users log on, since if they log on with no permissions they wouldn't get the access we were trying to provide them.

**Comment by BryceHolmes** [comment]
That's a great point, Andrew. We'll add a note to the content about this.
