### ISSUE TITLE
"Using Teams with Dynamics 365 Remote Assist " link returns 404 page not found for guest users

### ISSUE THREAD

**Issue by millenniumparade** [MicrosoftDocs/dynamics-365-mixed-reality#71]
The page is blank after signing in.
![Screenshot 2022-02-23 155943](https://user-images.githubusercontent.com/14156271/155409111-f835b8d5-fbf9-405c-a1af-f73000f3e159.png)

![Screenshot 2022-02-23 161045](https://user-images.githubusercontent.com/14156271/155409164-f4be48f3-a69e-4469-94cb-eb86be15f8fc.png)
![Screenshot 2022-02-23 161010](https://user-images.githubusercontent.com/14156271/155409195-c65ff937-3a42-4556-b3c3-bfacc71169f5.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a264db71-4fa7-3382-5d12-ec9bf35247fe
* Version Independent ID: 9e968d81-a530-009c-3245-4047a7c3659c
* Content: [Deploy Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/deploy-remote-assist)
* Content Source: [mr-docs/remote-assist/deploy-remote-assist.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/remote-assist/deploy-remote-assist.md)
* Service: **dynamics-365-remote-assist**
* GitHub Login: @amaraanigbo
* Microsoft Alias: **soanigbo**

**Comment by BryceHolmes** [comment]
Fixed
