### ISSUE TITLE
Content Migration Tool - Remove MFA remark

### ISSUE THREAD

**Issue by garrytrinder** [MicrosoftDocs/dynamics-365-mixed-reality#73]
In the documentation it suggests that accounts with MFA enabled are not supported, however this is not the case, I have just tested this in a development environment and with a customer, using MFA enabled accounts.

The authentication dialog in the tool is provided by `Microsoft.Xrm.Data.PowerShell` module which has supported MFA enabled accounts since April 2020, see https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/issues/261

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79b3fce-6157-aa9c-b264-e7b00fbc25a8
* Version Independent ID: 5bb88fef-4748-6948-e210-b1f0839acff7
* Content: [Migrate Dynamics 365 Guides content from one Microsoft Dataverse instance to another using the Content Migration Tool (Public Preview) - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/migrate)
* Content Source: [mr-docs/guides/migrate.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/guides/migrate.md)
* Service: **dynamics-365-guides**
* GitHub Login: @melissahellmund
* Microsoft Alias: **mehellmu**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @garrytrinder. This issue has been assigned to the doc author for review.

**Comment by BryceHolmes** [comment]
Thanks much, Garry, for these comments. We're working on updates.

**Comment by v-wendysmith** [comment]
@garrytrinder, hi, I'm new to the team and I'm following up on your comment. Thanks for pointing this out! We are removing that note from the documentation. Thanks for the feedback.
