### ISSUE TITLE
Figure 1.2 is not correct

### ISSUE THREAD

**Issue by mabrizi01** [MicrosoftDocs/dynamics-365-mixed-reality#74]
Hello all,
I would like to inform that the figure 1.2 is not correct, because in the box related to "Tenant Vendor 1", the second account is named "Vendor2_B@Vendor1.com" instead of "Vendor1_B@Vendor1.com". Following the line until to the box for "Tenant ABC" this is correctly named instead as "Vendor1_B_SA@Vendor1.com".
The same issue for the box "Tenant Vendor2", where the account is named "Vendor1_A@Vendor2.com" instead of "Vendor2_A@Vendor2.com". 

Regards,
Marco

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666c836d-443d-c966-d864-b5af63cbe2cb
* Version Independent ID: 67a9904a-6520-bf40-511a-2cebac571fc1
* Content: [Vendors and customers use full Dynamics 365 Remote Assist capabilities - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/vendor-use-ra)
* Content Source: [mr-docs/remote-assist/vendor-use-RA.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/remote-assist/vendor-use-RA.md)
* Service: **dynamics-365-remote-assist**
* GitHub Login: @amaraanigbo
* Microsoft Alias: **soanigbo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marcuss75. This issue has been assigned to the doc author for review.

**Comment by v-wendysmith** [comment]
Thank you for your feedback! Sorry for the delay, but we have fixed the diagram and the change is live now. Thanks again.

**Comment by v-wendysmith** [comment]
Doc updated
