### ISSUE TITLE
QR Code Link (HoloLens App) not correct

### ISSUE THREAD

**Issue by MezMarianne** [MicrosoftDocs/dynamics-365-mixed-reality#75]
Thank you for the guide and instructions for creating a collection of links to Dynamics 365 Guides.

I think have found an error in the guide.

The PC app link works fine, but the HoloLens App link does not work.
The PC app link is in this format: 
ms-guides://MY-ORG.crm4.dynamics.com/g/8921ce53-ee6b-4006-b173-1deba90c9101
and the HoloLens App link should be in this format:
ms-guides://MY-ORG.crm4.dynamics.com/g/nl-tt6A_vUy1cGeU3HlhEQ

However using your guide the HoloLens App link is 
https://api.qrserver.com/v1/create-qr-code/?qzone=4&size=1000x1000&bgcolor=666666&&data=ms-guides://MY-ORG.crm4.dynamics.com/g/8921ce53-ee6b-4006-b173-1deba90c9101
It works and creates a pretty QR code but it obviously reads as 
ms-guides://MY-ORG.crm4.dynamics.com/g/8921ce53-ee6b-4006-b173-1deba90c9101 in a QR scanner

This is not in the format ms-guides://MY-ORG.crm4.dynamics.com/g/nl-tt6A_vUy1cGeU3HlhEQ (letters and numbers but NOT a GUID) which would be the correct QR code link for the HoloLens.

I can se that the link to the HoloLens QR code/link is not saved in the Guides table in Dataverse. How do I get the value of the HoloLens link? I would like to know how to access the RANDOMSTRING which is the last bit of the Link to the guide. 

Is there a way to generate it based on the GUID of the Guide? Or is it just a random string? Any way to access the link besides manually right clicking on the guide and Copy Link?

Hope you can expand the guide on how to create the correct QR Code Link for the HoloLens App.

Kind regard
Marianne Lilholt
Donkey Power
--

</body>

</html>

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9716b57d-8fe1-3e11-8789-2b248a598c15
* Version Independent ID: 9f6c723c-0bbc-3e5f-b601-1ecb340abc22
* Content: [Workflow example 1--Automatically generate deeplinks for the Dynamics 365 Guides PC and HoloLens apps - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/guides/workflow-example-1)
* Content Source: [mr-docs/guides/workflow-example-1.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/guides/workflow-example-1.md)
* Service: **dynamics-365-guides**
* GitHub Login: @Mamaylya
* Microsoft Alias: **mamaylya**

**Comment by MezMarianne** [comment]
Hi there.
Two months since you assigned this to the doc author. How is the answer coming along? We really could use an instruction on how the "random string" part of the link to the guide is created.

Is there a way to generate it based on the GUID of the Guide? Or is it just a random string? Any way to access the link besides manually right clicking on the guide and Copy Link?

**Comment by MezMarianne** [comment]
Hi there
Five months since you assigned to the doc author. Have you had time to think of an answer? 
We have created a workaround where we manually cut and paste the link to the guide and then have a Power Automate Flow which turns it into an environment aware link. But it would be easier if the link was just the GUID in stead of a random string - or the random string was saved in Dataverse.

**Comment by v-wendysmith** [comment]
@Mamaylya Can you take a look at this request? If you could answer the questions, then I can update the documentation.

**Comment by MezMarianne** [comment]
@v-wendysmith @Mamaylya hope you have had a pleasant Christmas and New Year. How is the documentation on the link to a Dynamics Guide coming along?

**Comment by v-wendysmith** [comment]
@MezMarianne hope your new year has started off well. There are two different QR code link formats and both are equivalent. Both links contain the unique ID of the Guide record (a GUID). The compressed format contains the binary data of the GUID encoded in a way to minimize the total length. The second format contains the string version of the GUID (which results in a longer string).  I've discussed with the PM for Guides and we will be working on updating the documentation to explain the encoding process.

In the meantime, they have asked for you to open a support ticket so they can determine why the QR code isn't working in your HoloLens. Thank you for following up!

**Comment by m-hartmann** [comment]
@MezMarianne this took a while to resolve but we managed to release an update to the article based on your feedback. Thanks again for raising it and thanks to @v-wendysmith for completing the update. The refreshed article is going live later today. 

Thanks, 
Michael
