### ISSUE TITLE
Incorrect product name used in first paragraph of article

### ISSUE THREAD

**Issue by MadPrince** [MicrosoftDocs/dynamics-365-mixed-reality#87]
In the first paragraph of the article, it says "Dynamics 365 Remote Guides". This should instead say "Dynamics 365 Guides". 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf669126-c6ce-0d34-37a5-9c0a64137728
* Version Independent ID: cf669126-c6ce-0d34-37a5-9c0a64137728
* Content: [Collaborate with a Dynamics 365 Guides user from Microsoft Teams - Dynamics 365 Mixed Reality](https://learn.microsoft.com/en-us/dynamics365/mixed-reality/guides/calling-teams-users)
* Content Source: [mr-docs/guides/calling-teams-users.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/guides/calling-teams-users.md)
* Service: **dynamics-365-guides**
* GitHub Login: @davepinch
* Microsoft Alias: **davepinch**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MadPrince. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Ouch, thank you for spotting that, @MadPrince. Fix is rolling out in the next couple of hours.

Thanks, 
Michael
